#!/bin/bash

# This script is placed in the /usr/bin/ directory

if ! command -v docker; then
  echo "Install docker to run gtypist"
  exit 1
fi

echo "Launching gtypist..."

if [[ $# -gt 0 ]]; then
  docker container run --rm -it --name gtypist girishpasupathy/gtypist:latest gtypist "$*"
else
  docker container run --rm -it --name gtypist girishpasupathy/gtypist:latest
fi

exit
